name: pohlang
version: 0.3.5
description: "PohLang — a tiny, fully phrasal English-like language that transpiles to Dart."
homepage: https://github.com/AlhaqGH/PohLang
repository: https://github.com/AlhaqGH/PohLang
issue_tracker: https://github.com/AlhaqGH/PohLang/issues
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  collection: ^1.18.0
  path: ^1.9.0
dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.0

executables:
  pohlang: pohlang
