name: SDK Release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag (e.g., v0.5.2)'
        required: true
        type: string

permissions:
  contents: write

jobs:
  build-sdk:
    name: Build SDK (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            binary: pohlang
            platform: linux-x64
          - os: windows-latest
            binary: pohlang.exe
            platform: windows-x64
          - os: macos-latest
            binary: pohlang
            platform: macos-x64
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract tag
        id: tag
        shell: bash
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "tag=${{ github.event.inputs.tag }}" >> $GITHUB_OUTPUT
          else
            echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          fi

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build
        working-directory: runtime
        run: cargo build --release --verbose

      - name: Prepare SDK structure
        shell: bash
        run: |
          SDK_DIR="pohlang-sdk-${{ steps.tag.outputs.tag }}-${{ matrix.platform }}"
          mkdir -p "${SDK_DIR}"
          mkdir -p "${SDK_DIR}/bin"
          mkdir -p "${SDK_DIR}/lib"
          mkdir -p "${SDK_DIR}/include"
          mkdir -p "${SDK_DIR}/examples"
          mkdir -p "${SDK_DIR}/docs/api"
          mkdir -p "${SDK_DIR}/docs/spec"
          mkdir -p "${SDK_DIR}/docs/guide"
          
          # Copy runtime binary
          cp runtime/target/release/${{ matrix.binary }} "${SDK_DIR}/bin/"
          
          # Copy library (for embedding)
          if [ -f runtime/target/release/libpohlang_runtime.* ]; then
            cp runtime/target/release/libpohlang_runtime.* "${SDK_DIR}/lib/" || true
          fi
          
          # Copy examples
          cp -r examples/poh/* "${SDK_DIR}/examples/"
          
          # Copy language specification
          cp spec/Grammar.ebnf "${SDK_DIR}/docs/spec/"
          cp spec/Vocabulary.md "${SDK_DIR}/docs/spec/"
          
          # Copy user guide
          cp doc/PohLang_Guide.md "${SDK_DIR}/docs/guide/"
          
          # Copy design documents
          if [ -f runtime/DESIGN.md ]; then
            cp runtime/DESIGN.md "${SDK_DIR}/docs/api/Runtime_Design.md"
          fi
          
          # Copy README and LICENSE
          cp README.md "${SDK_DIR}/"
          cp LICENSE "${SDK_DIR}/"
          
          # Create SDK documentation
          cat > "${SDK_DIR}/SDK_README.md" << 'EOF'
          # PohLang Language SDK
          
          This is the **official PohLang Language SDK** for developers who want to:
          - Embed PohLang in their applications
          - Create language bindings for other languages
          - Build tools and extensions for PohLang
          - Study the language implementation
          
          ## Package Contents
          
          ### For End Users
          - `bin/` - PohLang runtime executable
          - `examples/` - Sample PohLang programs
          - `docs/guide/` - User documentation
          
          ### For Language Developers
          - `lib/` - Runtime libraries for embedding
          - `include/` - C/FFI headers (if available)
          - `docs/spec/` - Language specification (Grammar, Vocabulary)
          - `docs/api/` - Runtime design and architecture
          
          ## SDK Structure
          
          ```
          pohlang-sdk-{version}-{platform}/
          ├── bin/
          │   └── pohlang          # Runtime executable
          ├── lib/
          │   └── libpohlang_*     # Runtime library (for embedding)
          ├── include/             # Headers for FFI/embedding
          ├── examples/            # Sample .poh programs
          ├── docs/
          │   ├── guide/           # PohLang_Guide.md
          │   ├── spec/            # Grammar.ebnf, Vocabulary.md
          │   └── api/             # Runtime_Design.md
          ├── README.md
          ├── LICENSE
          └── SDK_README.md        # This file
          ```
          
          ## For End Users
          
          ### Running PohLang Programs
          
          ```bash
          # Windows
          bin\pohlang.exe examples\hello.poh
          
          # Linux/macOS  
          ./bin/pohlang examples/hello.poh
          ```
          
          See `docs/guide/PohLang_Guide.md` for language tutorials.
          
          ## For Language Developers
          
          ### Understanding PohLang
          
          1. **Language Specification** (`docs/spec/`)
             - `Grammar.ebnf` - Formal grammar in EBNF notation
             - `Vocabulary.md` - Keywords, operators, and syntax rules
          
          2. **Runtime Design** (`docs/api/`)
             - `Runtime_Design.md` - VM architecture and implementation
          
          3. **Examples** (`examples/`)
             - Study real PohLang programs to understand language features
          
          ### Embedding PohLang
          
          The runtime library in `lib/` allows you to embed PohLang in your applications.
          
          **Example (conceptual):**
          ```c
          #include "pohlang.h"
          
          int main() {
              pohlang_vm* vm = pohlang_vm_create();
              pohlang_vm_eval(vm, "Write 'Hello from embedded PohLang!'");
              pohlang_vm_destroy(vm);
              return 0;
          }
          ```
          
          ### Creating Language Bindings
          
          Use the specifications in `docs/spec/` to create parsers and tools:
          
          - **Python**: Create a PohLang parser using the EBNF grammar
          - **JavaScript**: Build a web-based PohLang interpreter
          - **Java/C#**: Integrate PohLang into JVM/.NET applications
          
          ### Building Tools
          
          The SDK provides everything needed to build:
          - **Syntax highlighters** (use Grammar.ebnf)
          - **LSP servers** (language server protocol)
          - **Code formatters** (based on syntax rules)
          - **Static analyzers** (using the specification)
          - **Transpilers** (PohLang to other languages)
          
          ## Language Specification Highlights
          
          From `docs/spec/Grammar.ebnf`:
          - Program structure: `Start Program ... End Program`
          - Variables: `Set name to value`
          - Functions: `Make functionName with params: ... End`
          - Control flow: `If condition ... End`, `While condition ... End`
          - Operations: Phrasal (`plus`, `minus`) and symbolic (`+`, `-`)
          
          ## Version Information
          
          This SDK corresponds to PohLang runtime version in the tag name.
          Check `bin/pohlang --version` for exact version details.
          
          ## Resources
          
          - **Repository**: https://github.com/AlhaqGH/PohLang
          - **Issues**: https://github.com/AlhaqGH/PohLang/issues
          - **Discussions**: https://github.com/AlhaqGH/PohLang/discussions
          
          ## License
          
          PohLang is released under the MIT License. See `LICENSE` file.
          
          ---
          
          **For questions about embedding or creating bindings, open a discussion on GitHub!**
          
          ## Getting Started (3 Steps)
          
          ### 1. Extract the Archive
          You've already done this if you're reading this file!
          
          ### 2. Run Your First Program
          
          **Windows:**
          ```cmd
          bin\pohlang.exe --run examples\hello.poh
          ```
          
          **Linux/macOS:**
          ```bash
          ./bin/pohlang --run examples/hello.poh
          ```
          
          ### 3. Create Your Own Program
          
          Create a file called `myprogram.poh`:
          
          ```
          Start Program
          
          Ask for name
          Write "Hello " plus name plus "!"
          
          Set count to 5
          Repeat count
              Write "PohLang is easy!"
          End
          
          End Program
          ```
          
          Run it:
          
          **Windows:**
          ```cmd
          bin\pohlang.exe --run myprogram.poh
          ```
          
          **Linux/macOS:**
          ```bash
          ./bin/pohlang --run myprogram.poh
          ```
          
          ## Optional: Add to System PATH
          
          For convenience, you can add PohLang to your system PATH so you can run it from anywhere.
          
          ### Windows
          1. Copy the full path to the `bin` folder (e.g., `C:\PohLang\bin`)
          2. Search for "Environment Variables" in Start menu
          3. Click "Environment Variables"
          4. Under "User variables", select "Path" and click "Edit"
          5. Click "New" and paste the path to the `bin` folder
          6. Click OK on all windows
          7. Open a new terminal and type: `pohlang --version`
          
          ### Linux/macOS
          ```bash
          # Option 1: Copy to /usr/local/bin (system-wide)
          sudo cp bin/pohlang /usr/local/bin/
          
          # Option 2: Add to ~/.bashrc or ~/.zshrc
          echo 'export PATH="$PATH:/full/path/to/pohlang-sdk/bin"' >> ~/.bashrc
          source ~/.bashrc
          
          # Test it
          pohlang --version
          ```
          
          ## Explore Examples
          
          The `examples/` folder contains many sample programs:
          
          - `hello.poh` - Simple hello world
          - `arithmetic.poh` - Math operations (both phrasal and symbolic)
          - `collections.poh` - Lists and dictionaries
          - `phrase_function.poh` - Function definitions
          - `phrase_logic.poh` - If statements and conditions
          - `phrase_repeat.poh` - Loops and repetition
          - `string_functions.poh` - String manipulation
          - And many more!
          
          Try them all:
          ```bash
          # Windows
          for %f in (examples\*.poh) do bin\pohlang.exe --run %f
          
          # Linux/macOS
          for f in examples/*.poh; do ./bin/pohlang --run "$f"; done
          ```
          
          ## Documentation
          
          - **`doc/PohLang_Guide.md`** - Complete language tutorial with examples
          - **`README.md`** - Project overview and feature list
          - **Online**: https://github.com/AlhaqGH/PohLang
          
          ## Learning Resources
          
          1. Start with `examples/hello.poh` - Basic syntax
          2. Read `doc/PohLang_Guide.md` - Full language guide
          3. Try `examples/phrase_logic.poh` - Learn conditionals
          4. Experiment with `examples/arithmetic.poh` - Math operations
          5. Build something cool!
          
          ## New in v0.5.2
          
          - ✅ **Symbolic operators**: Now supports `+`, `-`, `*`, `/`, `>`, `<`, `==`, `!=`
          - ✅ **Phrasal forms still work**: `plus`, `minus`, `times`, `is greater than`
          - ✅ **Mix both styles**: Use whichever you prefer!
          
          ```
          Start Program
          
          # Phrasal form
          Set a to 5 plus 3
          
          # Symbolic form
          Set b to 5 + 3
          
          # Both work!
          Write "a: " plus a
          Write "b: " plus b
          
          End Program
          ```
          
          ## Need Help?
          
          - **Issues**: https://github.com/AlhaqGH/PohLang/issues
          - **Discussions**: https://github.com/AlhaqGH/PohLang/discussions
          - **VS Code Extension**: https://marketplace.visualstudio.com/items?itemName=pohlang.pohlang-hub
          
          ## What's Next?
          
          - Write your own programs!
          - Share PohLang with friends learning to code
          - Report bugs or suggest features on GitHub
          - Check out the VS Code extension for a full IDE experience
          
          ---
          
          **Happy Coding with PohLang!** 🎉
          EOF
          
          echo "SDK_DIR=${SDK_DIR}" >> $GITHUB_ENV

      - name: Package SDK Linux/macOS
        if: matrix.os != 'windows-latest'
        run: |
          tar czf "${SDK_DIR}.tar.gz" "${SDK_DIR}"
          echo "ASSET_NAME=${SDK_DIR}.tar.gz" >> $GITHUB_ENV

      - name: Package SDK Windows
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          $SdkDir = $env:SDK_DIR
          $AssetName = "${SdkDir}.zip"
          Compress-Archive -Path $SdkDir -DestinationPath $AssetName
          echo "ASSET_NAME=${AssetName}" >> $env:GITHUB_ENV

      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          files: ${{ env.ASSET_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
